vim.opt.number = true          -- Show line numbers
vim.opt.relativenumber = false  -- Relative line numbers for easier navigation
vim.opt.mouse = 'a'            -- Enable mouse support
vim.opt.clipboard = 'unnamedplus' -- Use system clipboard
vim.opt.expandtab = true       -- Use spaces instead of tabs
vim.opt.tabstop = 2           -- Tab width
vim.opt.shiftwidth = 2        -- Indent width
vim.opt.autoindent = true     -- Auto-indent new lines
vim.opt.smartindent = true    -- Smart indenting
vim.opt.ignorecase = true     -- Case insensitive search
vim.opt.smartcase = true      -- Case sensitive if uppercase used
vim.opt.hlsearch = true       -- Highlight search results
vim.opt.incsearch = true      -- Show search matches as you type
vim.opt.cursorline = true     -- Highlight current line
vim.opt.wrap = false          -- Don't wrap lines
vim.opt.scrolloff = 8         -- Keep 8 lines visible above/below cursor
vim.opt.sidescrolloff = 8     -- Keep 8 columns visible left/right
vim.opt.signcolumn = 'yes'    -- Always show sign column
vim.opt.colorcolumn = '80'    -- Show column at 80 characters
vim.opt.updatetime = 250      -- Faster completion
vim.opt.timeoutlen = 300      -- Faster key sequence timeout
vim.opt.undofile = true       -- Persistent undo
vim.opt.swapfile = false      -- Disable swap files
vim.opt.backup = false        -- Disable backup files
vim.opt.splitbelow = true     -- Horizontal splits below
vim.opt.splitright = true     -- Vertical splits to the right
